version: '2'
services:
  ejemplojhispster_com-app:
    image: ejemplojhispster_com
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://ejemplojhispster_com-mysql:3306/ejemplojhispster_com?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://ejemplojhispster_com-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://ejemplojhispster_com-elasticsearch:9200
    ports:
      - 8080:8080
  ejemplojhispster_com-mysql:
    extends:
      file: mysql.yml
      service: ejemplojhispster_com-mysql
  ejemplojhispster_com-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: ejemplojhispster_com-elasticsearch
